# MSc Data Science Dissertation

## Station Matching

#### Name: Chandana Karunaratne
#### Student ID: 1621633
#### Date: 24 August 2017

In [ ]:
# The code below is used to match each station key with its corresponding name

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read in the necessary input files

station_entry_df = pd.read_csv("StationsOfEntry_CK1.csv")     # file containing all station of entry keys
station_exit_df = pd.read_csv("StationsOfExit_CK1.csv")       # file containing all station of exit keys
stationdic_df = pd.read_csv("StationsDictionary_CK1.csv")     # file containing station keys and their corresponding names

In [63]:
# Match each station of entry key with its corresponding name using the dictionary of stations

count = 0
dic_count = 0
station_name = 'not found'

while count < len(station_entry_df):
    dic_count = 0
    station_name = 'not found'
    while (dic_count < len(stationdic_df) and station_name == 'not found'):
        if station_entry_df['stationoffirstentrykey'][count] == stationdic_df['STATIONKEY'][dic_count]:
            station_entry_df['Station of Entry'][count] = stationdic_df['STATIONNAME'][dic_count]
            station_name = 'found'           
        dic_count = dic_count + 1
    count = count + 1

C:\Users\HP-PC\Anaconda2\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [64]:
# Show station_entry_df dataframe

station_entry_df

     stationoffirstentrykey        Station of Entry  Frequency  Percentage
0                        -1                       !  391467888     50.8973
1                         1              Acton Town     712592      0.0926
2                         2                Barbican    1265317      0.1645
3                         3                 Aldgate     783677      0.1019
4                         4            Aldgate East    1324129      0.1722
5                         5                Alperton     346593      0.0451
6                         7                   Angel    2233422      0.2904
7                         8                 Archway    1043171      0.1356
8                         9             Arnos Grove     567986      0.0738
9                        10                 Arsenal     433587      0.0564
10                       11            Baker Street    2971475      0.3863
11                       13                    Bank    3793605      0.4932
12                       16            Barons Court     934457      0.1215
13                       17               Bayswater     490045      0.0637
14                       18               Becontree     402425      0.0523
15                       19            Belsize Park     739621      0.0962
16                       22         Blackhorse Road    1014668      0.1319
17                       23             Bond Street    4336922      0.5639
18                       24                 Borough     569336      0.0740
19                       25            Boston Manor     254881      0.0331
20                       26            Bounds Green     770939      0.1002
21                       27                Bow Road     673234      0.0875
22                       28             Brent Cross     263658      0.0343
23                       30          Buckhurst Hill     249538      0.0324
24                       31               Burnt Oak     471594      0.0613
25                       32         Caledonian Road     754695      0.0981
26                       33             Camden Town    2064313      0.2684
27                       35             Canons Park     304220      0.0396
28                       37              Chalk Farm     663888      0.0863
29                       38           Chancery Lane    2054800      0.2672
..                      ...                     ...        ...         ...
651                    2093     Norwood Junction SR     489546      0.0636
652                    2094              Haggerston     357230      0.0464
653                    2095                  Hoxton     330588      0.0430
654                    2096                 Anerley      87544      0.0114
655                    2097                Brockley     561752      0.0730
656                    2098  Shoreditch High Street     804391      0.1046
657                    2099          Honor Oak Park     352268      0.0458
658                    2100             Sydenham SR     451183      0.0587
659                    2101             Rotherhithe     202808      0.0264
660                    2102             Shadwell LO     350653      0.0456
661                    2103            Surrey Quays     487799      0.0634
662                    2104                 Wapping     256772      0.0334
663                    2108        London Bridge NR    1037378      0.1349
664                    2114           Coulsdon Town      15264      0.0020
665                    2117          Bromley-by-Bow     405724      0.0528
666                    2118      Harrow-on-the-Hill    1096713      0.1426
667                    2123              Broxbourne      62282      0.0081
668                    2124                Cheshunt     104297      0.0136
669                    2125           Waltham Cross      53651      0.0070
670                    2126               Brentwood      95845      0.0125
671                    2127               Shenfield     117577      0.0153
672                    2128         Theobalds Grove      22563      0.0029
673                    2129     Clapham High Street     150221      0.0195
674                    2130         Wandsworth Road      80064      0.0104
675                    2131            Denmark Hill     619341      0.0805
676                    2132             Peckham Rye     790254      0.1027
677                    2133       Queens Rd Peckham     276131      0.0359
678                    2134                     NaN    2329095      0.3028
679                    2135                     NaN     259920      0.0338
680                    2136                     NaN    2555176      0.3322

[681 rows x 4 columns]

In [65]:
# Save the station_entry_df dataframe to an output file

station_entry_df.to_csv("StationsOfEntryNEW_CK1.csv", sep = '\t')

In [66]:
# Match each station of exit key with its corresponding name using the dictionary of stations

count = 0
dic_count = 0
station_name = 'not found'

while count < len(station_exit_df):
    dic_count = 0
    station_name = 'not found'
    while (dic_count < len(stationdic_df) and station_name == 'not found'):
        if station_exit_df['stationofexitkey'][count] == stationdic_df['STATIONKEY'][dic_count]:
            station_exit_df['Station of Exit'][count] = stationdic_df['STATIONNAME'][dic_count]
            station_name = 'found'           
        dic_count = dic_count + 1
    count = count + 1

C:\Users\HP-PC\Anaconda2\lib\site-packages\ipykernel\__main__.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [67]:
# Show station_exit_df dataframe

station_exit_df

     stationofexitkey         Station of Exit  Frequency  Percentage
0                  -1                       !  578483376     75.2123
1                   0                       ?        340      0.0000
2                   1              Acton Town     345446      0.0449
3                   2                Barbican     599793      0.0780
4                   3                 Aldgate     400454      0.0521
5                   4            Aldgate East     609693      0.0793
6                   5                Alperton     182099      0.0237
7                   7                   Angel    1057947      0.1376
8                   8                 Archway     480146      0.0624
9                   9             Arnos Grove     257885      0.0335
10                 10                 Arsenal     193516      0.0252
11                 11            Baker Street    1410636      0.1834
12                 13                    Bank    2038362      0.2650
13                 16            Barons Court     418454      0.0544
14                 17               Bayswater     228218      0.0297
15                 18               Becontree     185282      0.0241
16                 19            Belsize Park     348126      0.0453
17                 22         Blackhorse Road     457915      0.0595
18                 23             Bond Street    2042994      0.2656
19                 24                 Borough     279973      0.0364
20                 25            Boston Manor     125000      0.0163
21                 26            Bounds Green     355738      0.0463
22                 27                Bow Road     324261      0.0422
23                 28             Brent Cross     121098      0.0157
24                 30          Buckhurst Hill     121235      0.0158
25                 31               Burnt Oak     220491      0.0287
26                 32         Caledonian Road     331570      0.0431
27                 33             Camden Town    1077178      0.1401
28                 35             Canons Park     140717      0.0183
29                 37              Chalk Farm     274950      0.0357
..                ...                     ...        ...         ...
635              2093     Norwood Junction SR     187171      0.0243
636              2094              Haggerston     155473      0.0202
637              2095                  Hoxton     160185      0.0208
638              2096                 Anerley      32424      0.0042
639              2097                Brockley     227911      0.0296
640              2098  Shoreditch High Street     428207      0.0557
641              2099          Honor Oak Park     142657      0.0185
642              2100             Sydenham SR     185094      0.0241
643              2101             Rotherhithe      90900      0.0118
644              2102             Shadwell LO     278868      0.0363
645              2103            Surrey Quays     223491      0.0291
646              2104                 Wapping     120346      0.0156
647              2108        London Bridge NR    1117793      0.1453
648              2114           Coulsdon Town       6076      0.0008
649              2117          Bromley-by-Bow     188095      0.0245
650              2118      Harrow-on-the-Hill     571403      0.0743
651              2123              Broxbourne      23387      0.0030
652              2124                Cheshunt      41262      0.0054
653              2125           Waltham Cross      19737      0.0026
654              2126               Brentwood      37180      0.0048
655              2127               Shenfield      46865      0.0061
656              2128         Theobalds Grove       8122      0.0011
657              2129     Clapham High Street      94153      0.0122
658              2130         Wandsworth Road      30765      0.0040
659              2131            Denmark Hill     255122      0.0332
660              2132             Peckham Rye     328973      0.0428
661              2133       Queens Rd Peckham      99834      0.0130
662              2134                     NaN    1211911      0.1576
663              2135                     NaN     232683      0.0303
664              2136                     NaN        292      0.0000

[665 rows x 4 columns]

In [68]:
# Save station_exit_df dataframe as an output file

station_exit_df.to_csv("StationsOfExitNEW_CK1.csv", sep = '\t')